# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Satellite_passes
                                 A QGIS plugin
 Return next 10 day satellite passes. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-11
        copyright            : (C) 2024 by Ching Yin Kwok
        email                : ching.yin-kwok@ifgt.tu-freiberg.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Ching Yin Kwok'
__date__ = '2024-06-11'
__copyright__ = '(C) 2024 by Ching Yin Kwok'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Satellite_passes class from file Satellite_passes.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .satellite_passes import Satellite_passesPlugin
    return Satellite_passesPlugin()
